name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          filter: tree:0
          fetch-depth: 0

      # Cache node_modules
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - run: npm ci

      - run: npm exec nx format:check --base="origin/main" --head="HEAD"
      - run: npm exec nx -- run-many --targets=lint,build,typecheck
      - run: npm exec nx -- run-many --targets=test -- --coverage
      - uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: false
          verbose: true
      - run: npm run docs:check
      - run: npm run build -w apps/docs
        env:
          ASTRO_TELEMETRY_DISABLED: 1
